// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MangaCard { uuid: string, connector: string, title: string, cover: string, order: number, chapter: string, slide: number, }