// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "./Format";
import type { Integration } from "./Integration";

export interface MangaMeta { uuid: string, connector: string, order: number, chapter: string, slide: number, finished_chapters: Array<string>, format: Format, credits: string, integration: Integration, }