// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";
import type { MangaMeta } from "./MangaMeta";

export interface Manga { title: string, chapters: Array<Chapter>, path: string, meta: MangaMeta, }