// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuth } from "./OAuth";
import type { Reader } from "./Reader";

export interface Prefs { lang: string, manga_directory: string, discord_app_id: string, discord_rich_presence_enabled: boolean, oauth: OAuth, reader: Reader, }