// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { Format } from "./Format";

export interface Reader { direction: Direction, reverse: boolean, animation: boolean, animation_speed: number, default_format: Format, }